--- #That 3 "-" tell us this is a YMAL file.

- name: First apt example. #The name of playbook.
  hosts: web01 #Run the tasks on webserver1
  tasks:
    - name: Install php 7.2 #Headline of task
      apt:
        name: php7.2 #Name of the thing we want to download
        state: absent #Make it absent
        autoremove: true #Remove the installion
      become: true #Should be root for doing this
