--- #That 3 "-" tell us this is a YMAL file.

- name: First apt example. #The name of playbook.
  hosts: web01 #Run the tasks on webserver1
  tasks:
    - name: Install php 7.2
      apt:
        name: #We want to download multiple
          - php7.2
          - php7.2-mysql
        state: present #Latest version on the system
        update_cache: true #Do "apt-get update" thing
      become: true #Should be root for doing this
